### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by arumsey**
- update `package.json` for Caesars project

### CODE REVIEW

**Comment by arumsey** [comment]
@amol-anand Do you generally customize the package JSON coming from the boilerplate?

**Comment by amol-anand** [comment]
No, I've never updated package.json from boilerplate before.

**Comment by amol-anand** [comment]
It makes sense to update it, and it should not impact anything from what I can tell. Have you tested the hlx cli commands to see if anything is different?

**Review by amol-anand — APPROVED** [review]

**Comment by arumsey** [comment]
> It makes sense to update it, and it should not impact anything from what I can tell. Have you tested the hlx cli commands to see if anything is different?

I've tested locally and everything still works as expected.

**Pull request merged**
