### PR TITLE
Issue 178: slider fix mobile tablet view

### LINKED ISSUE #178: Slider: Fix mobile + tablet view for sliders
Screen Shot 2023-04-18 at 4 29 56 PM
Screen Shot 2023-04-18 at 4 30 10 PM
Screen Shot 2023-04-18 at 4 30 26 PM
Screen Shot 2023-04-18 at 4 30 39 PM

Screen Shot 2023-04-19 at 3 43 16 PM

Fix spacing and other text issues related to sliders.

### PR DESCRIPTION
**Pull request by swetabar**
Fix #178 

## 🔗 Test URLs:
  
- Before: https://main--caesars--hlxsites.hlx.page/caesars-palace/hotel
- After: https://issue-178-slider-fix-mobile-tablet-view--caesars--hlxsites.hlx.page/caesars-palace/hotel

## 📝 Description:
  
Screen Shot 2023-04-25 at 1 11 58 PM

Screen Shot 2023-04-25 at 1 12 30 PM

### CODE REVIEW

**Comment by swetabar** [comment]
Screen Shot 2023-04-25 at 1 13 42 PM

I'll work on the ellipses above once https://github.com/hlxsites/caesars/issues/197 is merged in.

**Review by tmathern — CHANGES_REQUESTED** [review]
For casinos, could you add the needed CSS to make sure images always have the same size?
See https://issue-178-slider-fix-mobile-tablet-view--caesars--hlxsites.hlx.page/caesars-palace/casino:
Screenshot 2023-04-25 at 10 21 19 AM

**Comment by swetabar** [comment]
> For casinos, could you add the needed CSS to make sure images always have the same size? See https://issue-178-slider-fix-mobile-tablet-view--caesars--hlxsites.hlx.page/caesars-palace/casino: Screenshot 2023-04-25 at 10 21 19 AM

@tmathern - Could you try: https://issue-178-slider-fix-mobile-tablet-view--caesars--hlxsites.hlx.page/caesars-palace/drafts/swbarman/casino? I'll move this casino page to the root from my drafts folder.

**Comment by swetabar** [comment]
> For casinos, could you add the needed CSS to make sure images always have the same size? See https://issue-178-slider-fix-mobile-tablet-view--caesars--hlxsites.hlx.page/caesars-palace/casino: Screenshot 2023-04-25 at 10 21 19 AM

Modified the authored content in the root page as well: https://issue-178-slider-fix-mobile-tablet-view--caesars--hlxsites.hlx.page/caesars-palace/casino

**Review by tmathern — APPROVED** [review]

**Pull request merged**
